"""create log_entries table

Revision ID: 148056c9f772
Revises: 
Create Date: 2026-03-19 12:26:51.976333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '148056c9f772'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_entries_environment'), 'log_entries', ['environment'], unique=False)
    op.create_index(op.f('ix_log_entries_event_type'), 'log_entries', ['event_type'], unique=False)
    op.create_index(op.f('ix_log_entries_id'), 'log_entries', ['id'], unique=False)
    op.create_index(op.f('ix_log_entries_severity'), 'log_entries', ['severity'], unique=False)
    op.create_index(op.f('ix_log_entries_source'), 'log_entries', ['source'], unique=False)
    op.create_index(op.f('ix_log_entries_timestamp'), 'log_entries', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_entries_timestamp'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_source'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_severity'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_id'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_event_type'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_environment'), table_name='log_entries')
    op.drop_table('log_entries')
    # ### end Alembic commands ###
